services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: sleep infinity
  localstack:
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - SERVICES=sqs
      - DEBUG=1
      - AWS_ACCESS_KEY_ID=000000000000
      - AWS_SECRET_ACCESS_KEY=000000000000
    volumes:
      - ./localstack:/etc/localstack/init/ready.d
      - localstack-data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  localstack-data:
