services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: sleep infinity
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_ENDPOINT_URL=${AWS_ENDPOINT_URL}
      - AWS_SQS_STRIPE_EVENTS_QUEUE_QUEUE_URL=${AWS_SQS_STRIPE_EVENTS_QUEUE_QUEUE_URL}
  localstack:
    build: ./localstack
    environment:
      - SERVICES=sqs
      - DEBUG=1
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ENDPOINT_URL=${AWS_ENDPOINT_URL}
      - AWS_REGION=${AWS_REGION}
      - AWS_SQS_STRIPE_EVENTS_QUEUE_QUEUE_NAME=${AWS_SQS_STRIPE_EVENTS_QUEUE_QUEUE_NAME}
    volumes:
      - localstack-data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
  stripe-cli:
    image: stripe/stripe-cli:latest
    entrypoint: stripe listen --forward-to http://app:8000
    environment:
      - STRIPE_API_KEY=${STRIPE_API_KEY}
volumes:
  localstack-data:
