services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: sleep infinity
  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - SERVICES=sqs
    volumes:
      - ./localstack/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh
      - localstack-data:/var/lib/localstack
volumes:
  localstack-data:
